services:
  postgres:
    image: postgres:16
    container_name: seat_pg
    environment:
      POSTGRES_DB: seatdb
      POSTGRES_USER: seatuser
      POSTGRES_PASSWORD: seatpass
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seatuser -d seatdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - seat_pg_data:/var/lib/postgresql/data

volumes:
  seat_pg_data: